/**
 * cssprobe-cli-cli Agent Skill templates.
 *
 * Installed into agent-specific skill directories via `cssprobe-cli-cli skill-install`.
 * Teaches agents how to use cssprobe-cli-cli for runtime CSS inspection — layout,
 * scroll, overflow, colors, backgrounds, fonts — with confidence levels.
 */

const FRONTMATTER_DELIM = '---';
const BT = '`';   // backtick
const BT3 = '```'; // triple backtick

export function buildSkillMd(): string {
  return [
    FRONTMATTER_DELIM,
    'name: cssprobe-cli-cli',
    'description: >',
    '  Runtime CSS probe for layout/scroll/overflow inspection. Use cssprobe-cli-cli to',
    '  diagnose CSS issues in live browsers — height chains, scroll containers,',
    '  overflow, flex constraints, containing block hijacks. Produces structured',
    '  reports with DEFINITE/INDEFINITE/UNVERIFIABLE confidence levels.',
    'metadata:',
    '  requires:',
    '    bins: ["cssprobe-cli-cli", "playwright"]',
    FRONTMATTER_DELIM,
    '',
    '# cssprobe-cli-cli -- Runtime CSS Probe Skill',
    '',
    'Use cssprobe-cli-cli to inspect the runtime CSS of any web page. It launches a real',
    'browser, captures computed styles and DOM structure, and produces a structured',
    'report with confidence levels.',
    '',
    '## Prerequisite: Browser Installation',
    '',
    'Before first use, install Chromium:',
    '',
    BT3 + 'bash',
    'npx playwright install chromium',
    BT3,
    '',
    'Verify: ' + BT + 'cssprobe-cli inspect https://getbootstrap.com/docs/5.3/examples/checkout body --json | head -5' + BT,
    '',
    '## Command Discovery',
    '',
    'Do NOT memorize all commands. Use:',
    '',
    BT3 + 'bash',
    'cssprobe-cli-cli --help                    # all commands grouped by category',
    'cssprobe-cli-cli inspect --help            # specific command: args, options, description',
    'cssprobe-cli-cli state-import --help       # cookie import command',
    BT3,
    '',
    '## Core Workflow: Inspect a Page',
    '',
    BT3 + 'bash',
    '# With explicit selector',
    'cssprobe-cli inspect https://getbootstrap.com/docs/5.3/examples/checkout body',
    '',
    '# Auto-detect root element (picks modal/dialog/scroll-container)',
    'cssprobe-cli inspect https://getbootstrap.com/docs/5.3/examples/checkout',
    '',
    '# Local HTML file',
    'cssprobe-cli inspect ./test.html ".container"',
    BT3,
    '',
    '## Login-Protected Pages',
    '',
    'Many pages require authentication. Three approaches:',
    '',
    '### Option A: Import cookies from browser export',
    '',
    BT3 + 'bash',
    '# 1. Export cookies from browser (Netscape format)',
    '# 2. Import into cssprobe-cli',
    'cssprobe-cli state-import cookies.txt --out ~/.cssprobe-cli/states/mysite.json',
    '',
    '# 3. Use the state file',
    'cssprobe-cli inspect https://mysite.com/page ".target" --state ~/.cssprobe-cli/states/mysite.json',
    BT3,
    '',
    '### Option B: Interactive login',
    '',
    BT3 + 'bash',
    'cssprobe-cli login https://mysite.com',
    '# Browser opens -> complete login manually -> press Enter',
    '# State saved to ~/.cssprobe-cli/states/mysite.com.json',
    '',
    'cssprobe-cli inspect https://mysite.com/page ".target" --state ~/.cssprobe-cli/states/mysite.com.json',
    BT3,
    '',
    '### Option C: Merge cookies into existing state',
    '',
    BT3 + 'bash',
    'cssprobe-cli state-import new-cookies.txt --merge existing.json --out merged.json',
    BT3,
    '',
    '## Wait for User Interaction',
    '',
    'For pages that require clicking a button or opening a dialog before inspection:',
    '',
    BT3 + 'bash',
    'cssprobe-cli inspect https://mysite.com/page ".dialog" --state ~/.cssprobe-cli/states/mysite.json --wait',
    '# Browser opens -> perform actions (click, open dialog) -> press Enter -> inspect',
    BT3,
    '',
    '## Interactive Mode (REPL)',
    '',
    'For inspecting multiple areas of the same page:',
    '',
    BT3 + 'bash',
    'cssprobe-cli interactive https://mysite.com --state ~/.cssprobe-cli/states/mysite.json',
    BT3,
    '',
    'Runtime commands:',
    '',
    BT3,
    'inspect> tree .dialog-A               # DOM tree',
    'inspect> layout .sidebar-B            # ASCII layout diagram',
    'inspect> sketch .content              # Tree sketch (issues only)',
    'inspect> findings .modal              # Findings only',
    'inspect> json .dialog-A               # JSON output',
    'inspect> report .dialog-A             # Full report',
    'inspect> .dialog-A                    # Shorthand for report',
    'inspect> navigate https://other.com   # Navigate to new URL',
    'inspect> depth 10                     # Set depth',
    'inspect> help                         # Show help',
    'inspect> quit                         # Exit',
    BT3,
    '',
    '## Output Modes',
    '',
    'Always pass ' + BT + '--json' + BT + ' when consuming output programmatically:',
    '',
    BT3 + 'bash',
    'cssprobe-cli inspect https://getbootstrap.com/docs/5.3/examples/checkout body --json',
    'cssprobe-cli inspect https://getbootstrap.com/docs/5.3/examples/checkout body --json | jq ' + BT + "'.findings[] | {id, confidence, message}'" + BT,
    BT3,
    '',
    'Without ' + BT + '--json' + BT + ', output is a Markdown report with ancestor chain,',
    'DOM tree, and findings with confidence labels.',
    '',
    '## Confidence Model',
    '',
    'Every finding carries a confidence level:',
    '',
    '| Level | Meaning |',
    '|-------|---------|',
    '| **DEFINITE** | Based on computed values (facts from getComputedStyle) or accessible declared values |',
    '| **INDEFINITE** | Declared value uses ' + BT + '%' + BT + ' -- resolves at runtime |',
    '| **UNVERIFIABLE** | Declared value missing or from blocked cross-origin stylesheet |',
    '',
    'The report header shows: ' + BT + 'confidence: DEFINITE 8 | INDEFINITE 0 | UNVERIFIABLE 1' + BT,
    '',
    '## inspect Options',
    '',
    BT3 + 'bash',
    'cssprobe-cli inspect <url> [selector] [options]',
    '',
    'Arguments:',
    '  <url>                       URL, file:// path, or local HTML file',
    '  [selector]                  CSS selector for root (auto-detected if omitted)',
    '',
    'Options:',
    '  --json                      Output structured JSON',
    '  --headed                    Show browser window',
    '  --browser <engine>          chromium|firefox|webkit (default chromium)',
    '  --zoom                      Run 1x/0.5x viewport diagnosis',
    '  --depth <n>                 DOM tree depth (default: auto)',
    '  --max-nodes <n>             Node count cap (default 60)',
    '  --up-to <tag>               Ancestor stop tag (default html)',
    '  --state <file>              Load saved state (cookies + localStorage)',
    '  --brief                     Compact output: tree sketch + warnings/errors only',
    '  --layout                    ASCII layout diagram showing element positions and sizes',
    '  --wait                      Wait for user interaction before collecting (implies --headed)',
    BT3,
    '',
    '## state-import: Netscape Cookie Format',
    '',
    BT3 + 'bash',
    '# From file',
    'cssprobe-cli state-import cookies.txt --out mystate.json',
    '',
    '# From stdin',
    'cat cookies.txt | cssprobe-cli state-import --out mystate.json',
    '',
    '# Merge into existing state',
    'cssprobe-cli state-import new-cookies.txt --merge existing.json --out merged.json',
    BT3,
    '',
    'Netscape format (tab-separated):',
    '',
    BT3,
    '.example.com\tTRUE\t/\tTRUE\t1813025057\tsession_id\tabc123',
    '.example.com\tTRUE\t/\tFALSE\t-1\tlang\tzh-CN',
    BT3,
    '',
    '## High-Frequency Workflows',
    '',
    '### 1. Diagnose layout/scroll issues',
    '',
    BT3 + 'bash',
    '# Inspect a specific component',
    'cssprobe-cli inspect https://app.example.com/page ".modal-body"',
    '',
    '# Get structured data for programmatic analysis',
    'cssprobe-cli --json inspect https://app.example.com/page ".modal-body" | jq ' + BT + "'.findings[]'" + BT,
    BT3,
    '',
    '### 2. Check if a page has overflow issues',
    '',
    BT3 + 'bash',
    '# Auto-detect and analyze',
    'cssprobe-cli inspect https://getbootstrap.com/docs/5.3/examples/checkout',
    '',
    '# Look for findings with level "warning" or "error"',
    'cssprobe-cli inspect https://getbootstrap.com/docs/5.3/examples/checkout body --json | jq ' + BT + "'.findings[] | select(.level != \"info\")'" + BT,
    BT3,
    '',
    '### 3. Inspect with authentication',
    '',
    BT3 + 'bash',
    '# Import cookies first',
    'cssprobe-cli state-import exported-cookies.txt --out ~/.cssprobe-cli/states/app.json',
    '',
    '# Then inspect with state',
    'cssprobe-cli inspect https://app.example.com/dashboard ".main-panel" --state ~/.cssprobe-cli/states/app.json',
    BT3,
    '',
    '### 4. Compare layouts at different viewports',
    '',
    BT3 + 'bash',
    '# Use --zoom to compare 1x vs 0.5x viewport',
    'cssprobe-cli inspect https://getbootstrap.com/docs/5.3/examples/checkout body --zoom',
    BT3,
    '',
    '## Anti-patterns',
    '',
    '- Always use ' + BT + '--json' + BT + ' when consuming output programmatically.',
    '- ' + BT + 'viewport-overflow' + BT + ' flags on elements below the fold are normal for scrolling pages -- not bugs.',
    '- Cross-origin stylesheet blocking is expected. Declared values from blocked sheets are',
    '  marked UNVERIFIABLE. Computed values from getComputedStyle() are still accurate.',
    '- ' + BT + '--auto-root' + BT + ' picks the first modal/dialog/scroll-container -- for specific elements,',
    '  provide an explicit selector.',
    '- Login state files contain cookies -- treat them as secrets.',
    '',
  ].join('\n');
}

export function buildPitfallsMd(): string {
  return [
    '# cssprobe-cli Pitfalls & Boundaries',
    '',
    '## Browser Installation',
    '',
    '- cssprobe-cli uses ' + BT + 'playwright-core' + BT + ' (not ' + BT + 'playwright' + BT + '). Browsers must be installed separately:',
    '  ' + BT + 'npx playwright install chromium' + BT,
    '- On macOS, Chromium is cached at ' + BT + '~/Library/Caches/ms-playwright/chromium-*' + BT + '.',
    '- cssprobe-cli auto-discovers existing Chromium installations in the Playwright cache.',
    '',
    '## Cross-origin Stylesheets',
    '',
    '- Browser security blocks ' + BT + 'cssRules' + BT + ' access on cross-origin stylesheets (CDN, third-party CSS).',
    '- Declared values from blocked sheets are marked ' + BT + 'UNVERIFIABLE' + BT + '.',
    '- Computed values from ' + BT + 'getComputedStyle()' + BT + ' are always accurate (not affected by CORS).',
    '- The report header shows: ' + BT + '⚠ N stylesheet(s) blocked by browser security' + BT + '.',
    '',
    '## Selector Not Found',
    '',
    '- If ' + BT + 'cssprobe-cli inspect <url> <selector>' + BT + ' returns ' + BT + '未找到 <selector>' + BT + ',',
    '  the element doesn\'t exist in the DOM at page load.',
    '- Use ' + BT + '--auto-root' + BT + ' (omit selector) to let cssprobe-cli pick a candidate.',
    '- For SPAs that load content dynamically, use ' + BT + '--headed' + BT + ' to see what\'s on the page.',
    '',
    '## Login State',
    '',
    '- State files contain cookies and localStorage -- treat them as secrets.',
    '- Cookies may expire -- re-import or re-login if inspection returns unexpected results.',
    '- ' + BT + 'state-import' + BT + ' expects Netscape cookie format (tab-separated).',
    '  Browser extensions like "EditThisCookie" or "Cookie Editor" can export in this format.',
    '',
    '## Viewport Overflow Flags',
    '',
    '- ' + BT + '⚠viewport-overflow' + BT + ' means the element\'s rect extends beyond the viewport.',
    '- For elements below the fold on scrolling pages, this is expected -- not a bug.',
    '- Focus on ' + BT + '⚠parent-overflow' + BT + ' and ' + BT + '⚠overflow(N>M)but-overflow=visible' + BT + ' for real issues.',
    '',
    '## Confidence Levels',
    '',
    '- ' + BT + 'DEFINITE' + BT + ': based on computed values (facts) or accessible declared values.',
    '- ' + BT + 'INDEFINITE' + BT + ': declared value uses ' + BT + '%' + BT + ' -- resolves at runtime.',
    '- ' + BT + 'UNVERIFIABLE' + BT + ': declared value missing or from blocked stylesheet.',
    '- When all ancestors have ' + BT + 'UNVERIFIABLE' + BT + ' height declarations, the anchor check',
    '  reports ' + BT + 'UNVERIFIABLE' + BT + ' -- this means we can\'t prove whether an anchor exists.',
    '',
    '## JSON Output',
    '',
    '- Pass ' + BT + '--json' + BT + ' BEFORE the command name: ' + BT + 'cssprobe-cli --json inspect <url>' + BT + '.',
    '- In JSON mode, errors are ' + BT + '{ "isError": true, "error": "message" }' + BT + ' and the',
    '  process exits with code 1. Check for ' + BT + 'isError' + BT + ' before parsing results.',
    '',
    '## Config',
    '',
    '- Config file: ' + BT + '~/.cssprobe-clirc' + BT + ' (JSON). Use ' + BT + 'config-path' + BT + ' to confirm.',
    '- Priority: CLI flags > env vars (' + BT + 'CSSPROBE_BROWSER' + BT + ', ' + BT + 'CSSPROBE_DEPTH' + BT + ',',
    '  ' + BT + 'CSSPROBE_HEADED' + BT + ') > config file.',
    '',
  ].join('\n');
}
