/**
 * cssprobe-cli Agent Skill templates.
 *
 * Installed into agent-specific skill directories via `cssprobe-cli skill-install`.
 * Teaches agents how to use cssprobe-cli for runtime CSS inspection — layout,
 * scroll, overflow, colors, backgrounds, fonts — with confidence levels.
 */

const FRONTMATTER_DELIM = '---';
const BT = '`';   // backtick
const BT3 = '```'; // triple backtick

export function buildSkillMd(): string {
  return [
    FRONTMATTER_DELIM,
    'name: cssprobe-cli',
    'description: >',
    '  Runtime CSS probe for layout/scroll/overflow inspection. Use cssprobe-cli to',
    '  diagnose CSS issues in live browsers — height chains, scroll containers,',
    '  overflow, flex constraints, containing block hijacks. Produces structured',
    '  reports with DEFINITE/INDEFINITE/UNVERIFIABLE confidence levels.',
    'metadata:',
    '  requires:',
    '    bins: ["cssprobe-cli", "playwright"]',
    FRONTMATTER_DELIM,
    '',
    '# cssprobe-cli -- Runtime CSS Probe Skill',
    '',
    'Use cssprobe-cli to inspect the runtime CSS of any web page. It launches a real',
    'browser, captures computed styles and DOM structure, and produces a structured',
    'report with confidence levels.',
    '',
    '## Prerequisite: Browser Installation',
    '',
    'Before first use, install Chromium:',
    '',
    BT3 + 'bash',
    'npx playwright install chromium',
    BT3,
    '',
    'Verify: ' + BT + 'cssprobe-cli status' + BT,
    '',
    '## Command Discovery',
    '',
    'Do NOT memorize all commands. Use:',
    '',
    BT3 + 'bash',
    'cssprobe-cli --help                    # all commands grouped by category',
    'cssprobe-cli inspect --help            # specific command: args, options, description',
    'cssprobe-cli state-import --help       # cookie import command',
    BT3,
    '',
    '## Core Workflow: Inspect a Page',
    '',
    'cssprobe-cli is session-based: ' + BT + 'open' + BT + ' starts a browser daemon, then',
    BT + 'inspect' + BT + ' / ' + BT + 'tree' + BT + ' / ' + BT + 'layout' + BT + ' / ' + BT + 'findings' + BT,
    'run against that session. Close the session with ' + BT + 'close' + BT + '.',
    '',
    BT3 + 'bash',
    '# 1. Open a page in a browser session',
    'cssprobe-cli open https://getbootstrap.com/docs/5.3/examples/checkout',
    '',
    '# 2. Inspect with an explicit selector',
    'cssprobe-cli inspect body',
    '',
    '# 3. Auto-detect: when the page has modals/dialogs, "open" already picks a root',
    '#    candidate, but inspect still needs a selector or auto-detection from candidates.',
    '#    For diagnosis without a selector, use "findings" after open.',
    '',
    '# 4. Close the session when done',
    'cssprobe-cli close',
    BT3,
    '',
    'For local HTML files:',
    '',
    BT3 + 'bash',
    'cssprobe-cli open ./test.html',
    'cssprobe-cli inspect ".container"',
    BT3,
    '',
    '## Login-Protected Pages',
    '',
    'Many pages require authentication. Two approaches:',
    '',
    '### Option A: Import cookies from browser export',
    '',
    BT3 + 'bash',
    '# 1. Export cookies from browser (Netscape format)',
    '# 2. Import into cssprobe-cli',
    'cssprobe-cli state-import cookies.txt --out ~/.cssprobe-cli/states/mysite.json',
    '',
    '# 3. Open the session with the saved state',
    'cssprobe-cli open https://mysite.com/page --state ~/.cssprobe-cli/states/mysite.json',
    'cssprobe-cli inspect ".target"',
    BT3,
    '',
    '### Option B: Interactive login',
    '',
    BT3 + 'bash',
    'cssprobe-cli open https://mysite.com --headed',
    '# Browser opens -> complete login manually',
    '',
    'cssprobe-cli inspect .target',
    BT3,
    '',
    '### Option C: Merge cookies into existing state',
    '',
    BT3 + 'bash',
    'cssprobe-cli state-import new-cookies.txt --merge existing.json --out merged.json',
    BT3,
    '',
    '## Session Mode (inspect multiple areas)',
    '',
    'Open once, run as many inspections as you need, then close:',
    '',
    BT3 + 'bash',
    'cssprobe-cli open https://mysite.com',
    '',
    'cssprobe-cli tree .dialog-A               # DOM tree',
    'cssprobe-cli layout .sidebar-B            # ASCII layout diagram',
    'cssprobe-cli findings .modal              # Findings only',
    'cssprobe-cli inspect .content --json      # JSON output',
    'cssprobe-cli inject-css ".sidebar { background: red; }"  # inject CSS to test changes',
    '',
    'cssprobe-cli close                         # stop browser + daemon',
    BT3,
    '',
    '## Output Modes',
    '',
    'Pass ' + BT + '--json' + BT + ' when consuming output programmatically:',
    '',
    BT3 + 'bash',
    'cssprobe-cli inspect body --json',
    'cssprobe-cli inspect body --json | jq ' + BT + "'.findings[] | {id, confidence, message}'" + BT,
    BT3,
    '',
    'Without ' + BT + '--json' + BT + ', output is a Markdown report with ancestor chain,',
    'DOM tree, and findings with confidence labels.',
    '',
    '## Confidence Model',
    '',
    'Every finding carries a confidence level:',
    '',
    '| Level | Meaning |',
    '|-------|---------|',
    '| **DEFINITE** | Based on computed values (facts from getComputedStyle) or accessible declared values |',
    '| **INDEFINITE** | Declared value uses ' + BT + '%' + BT + ' -- resolves at runtime |',
    '| **UNVERIFIABLE** | Declared value missing or from blocked cross-origin stylesheet |',
    '',
    'The report header shows: ' + BT + 'confidence: DEFINITE 8 | INDEFINITE 0 | UNVERIFIABLE 1' + BT,
    '',
    '## inspect Options',
    '',
    BT3 + 'bash',
    'cssprobe-cli inspect <selector> [options]',
    '',
    'Arguments:',
    '  <selector>                  CSS selector for the root element (required)',
    '',
    'Options:',
    '  --json                      Output structured JSON',
    '  --brief                     Compact output: tree sketch + warnings/errors only',
    '  --layout                    ASCII layout diagram showing element positions and sizes',
    '  --depth <n>                 DOM tree depth (default: auto)',
    BT3,
    '',
    '## open Options',
    '',
    BT3 + 'bash',
    'cssprobe-cli open <url> [options]',
    '',
    'Options:',
    '  --browser <engine>          chromium|firefox|webkit (default chromium)',
    '  --headed                    Show browser window',
    '  --viewport <WxH>            Viewport size, e.g. 1280x720',
    '  --state <file>              Load saved state (cookies + localStorage)',
    BT3,
    '',
    '## state-import: Netscape Cookie Format',
    '',
    BT3 + 'bash',
    '# From file',
    'cssprobe-cli state-import cookies.txt --out mystate.json',
    '',
    '# From file with custom name (saves to ~/.cssprobe-cli/states/<name>.json)',
    'cssprobe-cli state-import cookies.txt --name mysite',
    '',
    '# From stdin',
    'cat cookies.txt | cssprobe-cli state-import --out mystate.json',
    '',
    '# Merge into existing state',
    'cssprobe-cli state-import new-cookies.txt --merge existing.json --out merged.json',
    BT3,
    '',
    'Netscape format (tab-separated):',
    '',
    BT3,
    '.example.com\tTRUE\t/\tTRUE\t1813025057\tsession_id\tabc123',
    '.example.com\tTRUE\t/\tFALSE\t-1\tlang\tzh-CN',
    BT3,
    '',
    '## High-Frequency Workflows',
    '',
    '### 1. Diagnose layout/scroll issues',
    '',
    BT3 + 'bash',
    '# Inspect a specific component',
    'cssprobe-cli open https://app.example.com/page',
    'cssprobe-cli inspect ".modal-body"',
    '',
    '# Get structured data for programmatic analysis',
    'cssprobe-cli inspect ".modal-body" --json | jq ' + BT + "'.findings[]'" + BT,
    BT3,
    '',
    '### 2. Check if a page has overflow issues',
    '',
    BT3 + 'bash',
    '# Open and analyze',
    'cssprobe-cli open https://getbootstrap.com/docs/5.3/examples/checkout',
    '',
    '# Look for findings with level "warning" or "error"',
    'cssprobe-cli inspect body --json | jq ' + BT + "'.findings[] | select(.level != \"info\")'" + BT,
    BT3,
    '',
    '### 3. Inspect with authentication',
    '',
    BT3 + 'bash',
    '# Import cookies first',
    'cssprobe-cli state-import exported-cookies.txt --name app',
    '',
    '# Then open the session with state',
    'cssprobe-cli open https://app.example.com/dashboard --state ~/.cssprobe-cli/states/app.json',
    'cssprobe-cli inspect ".main-panel"',
    BT3,
    '',
    '## Anti-patterns',
    '',
    '- Always use ' + BT + '--json' + BT + ' when consuming output programmatically.',
    '- ' + BT + 'viewport-overflow' + BT + ' flags on elements below the fold are normal for scrolling pages -- not bugs.',
    '- Cross-origin stylesheet blocking is expected. Declared values from blocked sheets are',
    '  marked UNVERIFIABLE. Computed values from getComputedStyle() are still accurate.',
    '- Login state files contain cookies -- treat them as secrets.',
    '',
  ].join('\n');
}

export function buildPitfallsMd(): string {
  return [
    '# cssprobe-cli Pitfalls & Boundaries',
    '',
    '## Browser Installation',
    '',
    '- cssprobe-cli uses ' + BT + 'playwright-core' + BT + ' (not ' + BT + 'playwright' + BT + '). Browsers must be installed separately:',
    '  ' + BT + 'npx playwright install chromium' + BT,
    '- On macOS, Chromium is cached at ' + BT + '~/Library/Caches/ms-playwright/chromium-*' + BT + '.',
    '- cssprobe-cli auto-discovers existing Chromium installations in the Playwright cache.',
    '',
    '## Cross-origin Stylesheets',
    '',
    '- Browser security blocks ' + BT + 'cssRules' + BT + ' access on cross-origin stylesheets (CDN, third-party CSS).',
    '- Declared values from blocked sheets are marked ' + BT + 'UNVERIFIABLE' + BT + '.',
    '- Computed values from ' + BT + 'getComputedStyle()' + BT + ' are always accurate (not affected by CORS).',
    '- The report header shows: ' + BT + '⚠ N stylesheet(s) blocked by browser security' + BT + '.',
    '',
    '## Selector Not Found',
    '',
    '- If ' + BT + 'cssprobe-cli inspect <selector>' + BT + ' returns ' + BT + 'Not found: <selector>' + BT + ',',
    '  the element doesn\'t exist in the DOM at page load.',
    '- For SPAs that load content dynamically, use ' + BT + '--headed' + BT + ' to see what\'s on the page.',
    '',
    '## Login State',
    '',
    '- State files contain cookies and localStorage -- treat them as secrets.',
    '- Cookies may expire -- re-import or re-login if inspection returns unexpected results.',
    '- ' + BT + 'state-import' + BT + ' expects Netscape cookie format (tab-separated).',
    '  Browser extensions like "EditThisCookie" or "Cookie Editor" can export in this format.',
    '',
    '## Viewport Overflow Flags',
    '',
    '- ' + BT + '⚠viewport-overflow' + BT + ' means the element\'s rect extends beyond the viewport.',
    '- For elements below the fold on scrolling pages, this is expected -- not a bug.',
    '- Focus on ' + BT + '⚠parent-overflow' + BT + ' and ' + BT + '⚠overflow(N>M)but-overflow=visible' + BT + ' for real issues.',
    '',
    '## Confidence Levels',
    '',
    '- ' + BT + 'DEFINITE' + BT + ': based on computed values (facts) or accessible declared values.',
    '- ' + BT + 'INDEFINITE' + BT + ': declared value uses ' + BT + '%' + BT + ' -- resolves at runtime.',
    '- ' + BT + 'UNVERIFIABLE' + BT + ': declared value missing or from blocked stylesheet.',
    '- When all ancestors have ' + BT + 'UNVERIFIABLE' + BT + ' height declarations, the anchor check',
    '  reports ' + BT + 'UNVERIFIABLE' + BT + ' -- this means we can\'t prove whether an anchor exists.',
    '',
    '## JSON Output',
    '',
    '- Pass ' + BT + '--json' + BT + ' AFTER the command name: ' + BT + 'cssprobe-cli inspect body --json' + BT + '.',
    '- In JSON mode, errors are ' + BT + '{ "isError": true, "error": "message" }' + BT + ' and the',
    '  process exits with code 1. Check for ' + BT + 'isError' + BT + ' before parsing results.',
    '',
    '## Config',
    '',
    '- Config file: ' + BT + '~/.cssprobe-clirc' + BT + ' (JSON). Use ' + BT + 'config-path' + BT + ' to confirm.',
    '- Priority: CLI flags > env vars (' + BT + 'CSSPROBE_BROWSER' + BT + ', ' + BT + 'CSSPROBE_DEPTH' + BT + ',',
    '  ' + BT + 'CSSPROBE_HEADED' + BT + ') > config file.',
    '',
  ].join('\n');
}